import 'filter.dart';
import 'order_by.dart';
import 'return_mode.dart';

/// Annotates a method stub in a `.custom.dart` extension file to have
/// its implementation generated by suparepo.
///
/// The generated code builds a PostgREST query chain using the Supabase
/// Dart client.
///
/// ## Example
///
/// ```dart
/// extension HomeBannersRepositoryCustom on HomeBannersRepository {
///   @SupaQuery(
///     filters: [
///       Filter.eq('is_active', true),
///       Filter.lte('started_at', Param.now),
///       Filter.gt('ended_at', Param.now),
///     ],
///     order: [OrderBy('sort_order')],
///   )
///   Future<List<HomeBanners>> getActive() =>
///       throw UnimplementedError();
/// }
/// ```
///
/// Running `dart run suparepo` replaces the stub body with a real
/// Supabase query implementation.
class SupaQuery {
  /// Custom select expression. Defaults to `'*'` when omitted.
  ///
  /// Supports PostgREST relation syntax:
  /// ```dart
  /// select: 'id, name, products(image_url, name)'
  /// ```
  final String? select;

  /// Filters to apply to the query.
  final List<Filter> filters;

  /// Ordering clauses.
  final List<OrderBy> order;

  /// Maximum number of rows to return.
  final int? limit;

  /// How to return the result: [ReturnMode.list] (default),
  /// [ReturnMode.single], or [ReturnMode.maybeSingle].
  final ReturnMode returnMode;

  /// The name of a custom result model class.
  ///
  /// When set, the generated code uses `ResultModel.fromJson(e)` (or
  /// `.fromRow(e)`) instead of the table's default model.
  final String? resultModel;

  /// Creates a [SupaQuery] annotation.
  const SupaQuery({
    this.select,
    this.filters = const [],
    this.order = const [],
    this.limit,
    this.returnMode = ReturnMode.list,
    this.resultModel,
  });
}
