import 'package:recase/recase.dart';
import 'edge_function_info.dart';

/// Generates Freezed success-response DTOs for Edge Functions.
///
/// One file per function (`<function_name>_response.dart`) containing a
/// json_serializable Freezed class (plus nested classes for nested objects).
/// snake_case keys are mapped with `@JsonKey(name: ...)`, `T | null` fields
/// become nullable, and `string[]` becomes `List<String>`.
///
/// Because the source interface describes the *actual* response shape (partial
/// projections + computed fields), the generated `fromJson` parses real
/// responses without throwing: required fields are always present and the
/// optional/nullable ones tolerate missing keys.
class EdgeFunctionResponseGenerator {
  const EdgeFunctionResponseGenerator();

  /// Dart class name for a function's response DTO.
  /// e.g. `get_daily_card` → `GetDailyCardResponse`.
  static String responseClassName(String functionName) =>
      '${ReCase(functionName).pascalCase}Response';

  /// File name for a function's response DTO.
  /// e.g. `get_daily_card` → `get_daily_card_response.dart`.
  static String responseFileName(String functionName) =>
      '${ReCase(functionName).snakeCase}_response.dart';

  /// Generates the response DTO file content for [functionName] from its
  /// recovered [fields]. Returns null when [fields] is empty.
  String? generateResponseModel(
    String functionName,
    List<EdgeFunctionResponseField> fields,
  ) {
    if (fields.isEmpty) return null;

    final className = responseClassName(functionName);
    final snakeName = ReCase(functionName).snakeCase;
    final buffer = StringBuffer();

    // Header
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by suparepo');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln(
      '// ignore_for_file: public_member_api_docs, '
      'sort_constructors_first, lines_longer_than_80_chars, '
      'invalid_annotation_target',
    );
    buffer.writeln();

    // Imports / parts
    buffer.writeln(
      "import 'package:freezed_annotation/freezed_annotation.dart';",
    );
    buffer.writeln();
    buffer.writeln("part '${snakeName}_response.freezed.dart';");
    buffer.writeln("part '${snakeName}_response.g.dart';");
    buffer.writeln();

    buffer.writeln(
      '/// Success response DTO for the `$functionName` Edge Function.',
    );

    // Root + nested classes (depth-first, declared after their parent).
    _writeClass(buffer, className, fields);

    return buffer.toString();
  }

  void _writeClass(
    StringBuffer buffer,
    String className,
    List<EdgeFunctionResponseField> fields,
  ) {
    buffer.writeln('@freezed');
    buffer.writeln('abstract class $className with _\$$className {');
    buffer.writeln('  const factory $className({');

    for (final field in fields) {
      final fieldName = ReCase(field.jsonKey).camelCase;
      final type = _fieldType(className, field);
      final jsonKeyAnno =
          fieldName != field.jsonKey ? "@JsonKey(name: '${field.jsonKey}') " : '';
      if (field.nullable) {
        // `dynamic` is already nullable; `dynamic?` is a lint, so omit the `?`
        // (and the field stays optional without `required`).
        final nullableType = type == 'dynamic' ? 'dynamic' : '$type?';
        buffer.writeln('    $jsonKeyAnno$nullableType $fieldName,');
      } else {
        buffer.writeln('    ${jsonKeyAnno}required $type $fieldName,');
      }
    }

    buffer.writeln('  }) = _$className;');
    buffer.writeln();
    buffer.writeln(
      '  factory $className.fromJson(Map<String, dynamic> json) =>',
    );
    buffer.writeln('      _\$${className}FromJson(json);');
    buffer.writeln('}');

    // Emit nested object classes referenced by this class.
    for (final field in fields) {
      if (!field.isObject) continue;
      buffer.writeln();
      _writeClass(
        buffer,
        _nestedClassName(className, field),
        field.objectFields!,
      );
    }
  }

  /// Resolved Dart type for a field, including List/nullable wrapping.
  String _fieldType(String ownerClass, EdgeFunctionResponseField field) {
    var base = field.isObject
        ? _nestedClassName(ownerClass, field)
        : field.dartScalarType!;
    if (field.isList) base = 'List<$base>';
    return base;
  }

  /// Nested class name: object → `<Owner><Key>`, list item → `<Owner><Key>Item`.
  String _nestedClassName(String ownerClass, EdgeFunctionResponseField field) {
    final keyPart = ReCase(field.jsonKey).pascalCase;
    return field.isList ? '$ownerClass${keyPart}Item' : '$ownerClass$keyPart';
  }

  /// Generates response DTO files for all functions that have a recovered
  /// response object. Returns a map of file name → content.
  Map<String, String> generateAllResponseModels(
    Map<String, EdgeFunctionModelDef> modelDefs,
  ) {
    final result = <String, String>{};
    for (final entry in modelDefs.entries) {
      final fields = entry.value.responseObject;
      if (fields == null || fields.isEmpty) continue;
      final content = generateResponseModel(entry.key, fields);
      if (content != null) {
        result[responseFileName(entry.key)] = content;
      }
    }
    return result;
  }
}
