import 'package:recase/recase.dart';
import 'config_loader.dart';
import 'edge_function_info.dart';

/// Generates a Supabase Edge Function client class
class EdgeFunctionGenerator {
  /// Generates the client file content
  ///
  /// If [modelDefs] is provided, typed request/response classes
  /// are used for functions that have model definitions.
  String generateEdgeFunctionClient(
    List<EdgeFunctionInfo> functions, {
    Map<String, EdgeFunctionModelDef>? modelDefs,
    String supabaseImport = defaultSupabaseImport,
  }) {
    final buffer = StringBuffer();

    // Header
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by suparepo');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln(
      '// ignore_for_file: public_member_api_docs, '
      'sort_constructors_first, lines_longer_than_80_chars',
    );
    buffer.writeln();

    // Imports
    buffer.writeln("import '$supabaseImport';");

    // dart:convert is only used when a typed response is decoded
    // (jsonDecode + utf8.decode). Request-only models don't need it.
    final hasResponseModels = modelDefs != null &&
        functions.any((f) => modelDefs[f.name]?.response != null);
    if (hasResponseModels) {
      buffer.writeln(
        "import 'dart:convert';",
      );
    }

    buffer.writeln();

    // Generate model classes if needed
    if (modelDefs != null) {
      for (final func in functions) {
        final modelDef = modelDefs[func.name];
        if (modelDef == null) continue;

        final baseName = ReCase(func.name).pascalCase;

        if (modelDef.request != null) {
          _generateModelClass(
            buffer,
            '${baseName}Request',
            modelDef.request!,
          );
          buffer.writeln();
        }
        if (modelDef.response != null) {
          _generateModelClass(
            buffer,
            '${baseName}Response',
            modelDef.response!,
          );
          buffer.writeln();
        }
      }
    }

    // Class definition
    buffer.writeln(
      '/// Type-safe Edge Function client for Supabase',
    );
    buffer.writeln('class SupabaseEdgeFunctionClient {');
    buffer.writeln('  final SupabaseClient _client;');
    buffer.writeln();
    buffer.writeln(
      '  const SupabaseEdgeFunctionClient(this._client);',
    );

    for (final func in functions) {
      buffer.writeln();
      final modelDef = modelDefs?[func.name];
      if (modelDef != null &&
          (modelDef.request != null || modelDef.response != null)) {
        _generateTypedMethod(buffer, func, modelDef);
      } else {
        _generateUntypedMethod(buffer, func);
      }
    }

    buffer.writeln('}');

    return buffer.toString();
  }

  void _generateUntypedMethod(
    StringBuffer buffer,
    EdgeFunctionInfo func,
  ) {
    final methodName = ReCase(func.name).camelCase;

    if (func.description != null) {
      buffer.writeln('  /// ${func.description}');
    }

    buffer.writeln(
      '  Future<FunctionResponse> $methodName({',
    );
    buffer.writeln('    Map<String, dynamic>? body,');
    buffer.writeln('    Map<String, String>? headers,');
    buffer.writeln('  }) async {');
    buffer.writeln(
      "    return await _client.functions.invoke("
      "'${func.name}', body: body, headers: headers);",
    );
    buffer.writeln('  }');
  }

  void _generateTypedMethod(
    StringBuffer buffer,
    EdgeFunctionInfo func,
    EdgeFunctionModelDef modelDef,
  ) {
    final methodName = ReCase(func.name).camelCase;
    final baseName = ReCase(func.name).pascalCase;

    final hasRequest = modelDef.request != null;
    final hasResponse = modelDef.response != null;
    final returnType = hasResponse ? '${baseName}Response' : 'FunctionResponse';

    if (func.description != null) {
      buffer.writeln('  /// ${func.description}');
    }

    buffer.write('  Future<$returnType> $methodName({');
    buffer.writeln();
    if (hasRequest) {
      buffer.writeln(
        '    required ${baseName}Request request,',
      );
    }
    buffer.writeln('    Map<String, String>? headers,');
    buffer.writeln('  }) async {');

    buffer.writeln(
      '    final response = await _client.functions.invoke(',
    );
    buffer.writeln("      '${func.name}',");
    if (hasRequest) {
      buffer.writeln('      body: request.toJson(),');
    }
    buffer.writeln('      headers: headers,');
    buffer.writeln('    );');

    if (hasResponse) {
      buffer.writeln('    final data = response.data;');
      buffer.writeln(
        '    final json = data is List<int>',
      );
      buffer.writeln(
        '        ? jsonDecode(utf8.decode(data))'
        ' as Map<String, dynamic>',
      );
      buffer.writeln(
        '        : data as Map<String, dynamic>;',
      );
      buffer.writeln(
        '    return ${baseName}Response.fromJson(json);',
      );
    } else {
      buffer.writeln('    return response;');
    }

    buffer.writeln('  }');
  }

  void _generateModelClass(
    StringBuffer buffer,
    String className,
    List<EdgeFunctionFieldDef> fields,
  ) {
    final dartType = _pgTypeToDartType;

    buffer.writeln('class $className {');

    // Fields
    for (final field in fields) {
      final type = dartType(field.dataType);
      if (field.isRequired) {
        buffer.writeln(
          '  final $type ${ReCase(field.name).camelCase};',
        );
      } else {
        buffer.writeln(
          '  final $type? ${ReCase(field.name).camelCase};',
        );
      }
    }
    buffer.writeln();

    // Constructor
    buffer.writeln('  const $className({');
    for (final field in fields) {
      final paramName = ReCase(field.name).camelCase;
      if (field.isRequired) {
        buffer.writeln('    required this.$paramName,');
      } else {
        buffer.writeln('    this.$paramName,');
      }
    }
    buffer.writeln('  });');
    buffer.writeln();

    // fromJson
    buffer.writeln(
      '  factory $className.fromJson('
      'Map<String, dynamic> json) {',
    );
    buffer.writeln('    return $className(');
    for (final field in fields) {
      final paramName = ReCase(field.name).camelCase;
      final type = dartType(field.dataType);
      buffer.writeln(
        "      $paramName: json['${field.name}'] as $type"
        '${field.isRequired ? '' : '?'},',
      );
    }
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln();

    // toJson
    buffer.writeln(
      '  Map<String, dynamic> toJson() {',
    );
    buffer.writeln('    return {');
    for (final field in fields) {
      final paramName = ReCase(field.name).camelCase;
      if (field.isRequired) {
        buffer.writeln(
          "      '${field.name}': $paramName,",
        );
      } else {
        buffer.writeln(
          "      if ($paramName != null) "
          "'${field.name}': $paramName,",
        );
      }
    }
    buffer.writeln('    };');
    buffer.writeln('  }');

    buffer.writeln('}');
  }

  /// Generates Freezed sealed error class for a single Edge Function
  ///
  /// Returns the file content or null if there are no error definitions.
  String? generateErrorClass(
    String functionName,
    List<EdgeFunctionErrorDef> errors, {
    String supabaseImport = defaultSupabaseImport,
  }) {
    if (errors.isEmpty) return null;

    final baseName = ReCase(functionName).pascalCase;
    final className = '${baseName}Error';
    final snakeName = ReCase(functionName).snakeCase;
    final buffer = StringBuffer();

    // Header
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by suparepo');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln(
      '// ignore_for_file: public_member_api_docs, '
      'sort_constructors_first, lines_longer_than_80_chars',
    );
    buffer.writeln();

    // Imports
    buffer.writeln(
      "import 'package:freezed_annotation/freezed_annotation.dart';",
    );
    buffer.writeln("import '$supabaseImport';");
    buffer.writeln("import 'dart:convert';");
    buffer.writeln();
    buffer.writeln("part '${snakeName}_error.freezed.dart';");
    buffer.writeln();

    // Sealed class
    buffer.writeln('@freezed');
    buffer.writeln(
      'sealed class $className with _\$$className {',
    );
    buffer.writeln('  const $className._();');
    buffer.writeln();

    // Named constructors for each error code
    for (final error in errors) {
      final factoryName = ReCase(error.code).camelCase;
      final subclassName = '$className${ReCase(error.code).pascalCase}';
      buffer.writeln('  const factory $className.$factoryName({');
      buffer.writeln('    required int status,');
      buffer.writeln('    required String message,');
      buffer.writeln('  }) = $subclassName;');
      buffer.writeln();
    }

    // Unknown variant
    buffer.writeln('  const factory $className.unknown({');
    buffer.writeln('    required int status,');
    buffer.writeln('    required String errorCode,');
    buffer.writeln('    required String message,');
    buffer.writeln('  }) = ${className}Unknown;');
    buffer.writeln();

    // fromFunctionException factory
    buffer.writeln(
      '  factory $className.fromFunctionException(',
    );
    buffer.writeln('    FunctionException e,');
    buffer.writeln('  ) {');
    buffer.writeln('    final details = e.details;');
    buffer.writeln('    final body = switch (details) {');
    buffer.writeln(
      '      final String s => jsonDecode(s)'
      ' as Map<String, dynamic>,',
    );
    buffer.writeln(
      '      final Map<String, dynamic> m => m,',
    );
    buffer.writeln('      _ => <String, dynamic>{},');
    buffer.writeln('    };');
    buffer.writeln(
      "    final code = body['error'] as String? ?? '';",
    );
    buffer.writeln(
      "    final msg = body['message'] as String? ?? code;",
    );
    buffer.writeln('    return switch (code) {');

    for (final error in errors) {
      final factoryName = ReCase(error.code).camelCase;
      buffer.writeln("      '${error.code}' =>");
      buffer.writeln(
        '        $className.$factoryName(',
      );
      buffer.writeln(
        '          status: e.status, message: msg,',
      );
      buffer.writeln('        ),');
    }

    buffer.writeln('      _ => $className.unknown(');
    buffer.writeln(
      '          status: e.status, errorCode: code, '
      'message: msg,',
    );
    buffer.writeln('        ),');
    buffer.writeln('    };');
    buffer.writeln('  }');

    buffer.writeln('}');

    return buffer.toString();
  }

  /// Generates error classes for all Edge Functions that have errors.
  ///
  /// Returns a map of filename -> content.
  Map<String, String> generateErrorClasses(
    Map<String, EdgeFunctionModelDef> modelDefs, {
    String supabaseImport = defaultSupabaseImport,
  }) {
    final result = <String, String>{};

    for (final entry in modelDefs.entries) {
      final errors = entry.value.errors;
      if (errors == null || errors.isEmpty) continue;

      final snakeName = ReCase(entry.key).snakeCase;
      final fileName = '${snakeName}_error.dart';
      final content = generateErrorClass(
        entry.key,
        errors,
        supabaseImport: supabaseImport,
      );
      if (content != null) {
        result[fileName] = content;
      }
    }

    return result;
  }

  static String Function(String) get _pgTypeToDartType =>
      (String pgType) => switch (pgType) {
            'text' || 'varchar' || 'uuid' => 'String',
            'int4' || 'int8' || 'integer' || 'bigint' => 'int',
            'float4' || 'float8' || 'numeric' || 'double' => 'double',
            'bool' || 'boolean' => 'bool',
            'json' || 'jsonb' => 'Map<String, dynamic>',
            'timestamp' || 'timestamptz' || 'date' => 'String',
            _ => 'dynamic',
          };
}
