import 'package:recase/recase.dart';
import 'package:supabase_schema_core/supabase_schema_core.dart';
import 'config_loader.dart';
import 'custom_method_migrator.dart';

/// Generates repository code from table information
class RepositoryGenerator {
  /// Configuration for generation
  SuparepoConfig? _config;

  /// Supabase package import path
  String _supabaseImport = defaultSupabaseImport;

  /// Sets the configuration
  void setConfig(SuparepoConfig config) {
    _config = config;
    _supabaseImport = config.supabaseImport;
  }

  /// Whether typed model classes are available
  bool get _hasModelImport =>
      _config?.modelImportPrefix != null || _config?.modelImportPath != null;

  /// Gets the class name for a table's model
  String getModelClassName(String tableName) {
    return ReCase(tableName).pascalCase;
  }

  /// Gets the repository class name for a table
  String getRepositoryClassName(String tableName) {
    return '${ReCase(tableName).pascalCase}Repository';
  }

  /// Gets the file name for a repository
  String getFileName(String tableName) {
    return '${ReCase(tableName).snakeCase}_repository.dart';
  }

  /// Gets the fake repository class name for a table
  String getFakeClassName(String tableName) {
    return 'Fake${ReCase(tableName).pascalCase}Repository';
  }

  /// Gets the fake repository file name for a table
  String getFakeFileName(String tableName) {
    return '${ReCase(tableName).snakeCase}_repository.fake.dart';
  }

  /// Generates a repository file content for a single table.
  ///
  /// When [customContent] is provided, the custom methods/fields from
  /// the `.custom.dart` extension file are embedded as real instance
  /// methods in the generated class.
  String generateRepository(
    TableInfo table, {
    CustomFileContent? customContent,
  }) {
    final modelClassName = getModelClassName(table.name);
    final repoClassName = getRepositoryClassName(table.name);
    final tableName = table.name;

    // Find primary key column
    final primaryKey = table.columns.firstWhere(
      (c) => c.isPrimaryKey,
      orElse: () => table.columns.firstWhere(
        (c) => c.name == 'id',
        orElse: () => table.columns.first,
      ),
    );
    final pkName = primaryKey.name;
    final pkDartType = TypeMapper.mapType(primaryKey.dataType);

    final buffer = StringBuffer();

    // Header
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by suparepo');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln(
      '// ignore_for_file: public_member_api_docs, '
      'sort_constructors_first, lines_longer_than_80_chars',
    );
    buffer.writeln(
      '// ignore_for_file: directives_ordering, '
      'unnecessary_lambdas, avoid_redundant_argument_values',
    );
    buffer.writeln();

    // Imports
    if (_config?.generateProviders == true) {
      buffer.writeln(
        "import 'package:riverpod_annotation/riverpod_annotation.dart';",
      );
    }
    buffer.writeln("import '$_supabaseImport';");

    // Model import: prefix-based (individual files) or barrel
    if (_config?.modelImportPrefix != null) {
      final modelFile = '${ReCase(table.name).snakeCase}.supafreeze.dart';
      buffer.writeln(
        "import '${_config!.modelImportPrefix}$modelFile';",
      );
    } else if (_hasModelImport) {
      buffer.writeln("import '${_config!.modelImportPath}';");
    }

    // Custom imports from .custom.dart (excluding already-present imports)
    if (customContent != null) {
      final existingCode = buffer.toString();
      for (final imp in customContent.imports) {
        if (!existingCode.contains(imp)) {
          buffer.writeln(imp);
        }
      }
    }

    if (_config?.generateProviders == true) {
      buffer.writeln();
      final fileName = ReCase(table.name).snakeCase;
      final providerImport =
          _config?.clientProviderImport ?? 'supabase_client_provider.dart';
      buffer.writeln("import '$providerImport';");
      buffer.writeln();
      buffer.writeln("part '${fileName}_repository.g.dart';");
    }
    buffer.writeln();

    // Class definition
    buffer.writeln('/// Repository for $tableName table');
    buffer.writeln('class $repoClassName {');
    buffer.writeln('  final SupabaseClient _client;');
    buffer.writeln();
    buffer.writeln('  $repoClassName(this._client);');
    buffer.writeln();

    // Table name getter
    buffer.writeln("  String get tableName => '$tableName';");

    // Public client getter for extensions
    buffer.writeln();
    buffer.writeln('  /// SupabaseClient accessor for custom extensions.');
    buffer.writeln('  SupabaseClient get client => _client;');
    buffer.writeln();

    // getAll method
    buffer.writeln('  /// Fetches all records from $tableName');
    if (_hasModelImport) {
      buffer.writeln('  Future<List<$modelClassName>> getAll() async {');
      buffer.writeln(
          "    final response = await _client.from(tableName).select();");
      buffer.writeln(
          '    return response.map((e) => $modelClassName.fromJson(e)).toList();');
    } else {
      buffer.writeln('  Future<List<Map<String, dynamic>>> getAll() async {');
      buffer.writeln(
          "    final response = await _client.from(tableName).select();");
      buffer.writeln('    return response;');
    }
    buffer.writeln('  }');
    buffer.writeln();

    // getById method
    buffer.writeln('  /// Fetches a single record by $pkName');
    if (_hasModelImport) {
      buffer.writeln(
          '  Future<$modelClassName?> getById($pkDartType $pkName) async {');
      buffer.writeln('    final response = await _client');
      buffer.writeln('        .from(tableName)');
      buffer.writeln('        .select()');
      buffer.writeln("        .eq('$pkName', $pkName)");
      buffer.writeln('        .maybeSingle();');
      buffer.writeln(
          '    return response != null ? $modelClassName.fromJson(response) : null;');
    } else {
      buffer.writeln(
          '  Future<Map<String, dynamic>?> getById($pkDartType $pkName) async {');
      buffer.writeln('    final response = await _client');
      buffer.writeln('        .from(tableName)');
      buffer.writeln('        .select()');
      buffer.writeln("        .eq('$pkName', $pkName)");
      buffer.writeln('        .maybeSingle();');
      buffer.writeln('    return response;');
    }
    buffer.writeln('  }');
    buffer.writeln();

    // create method
    buffer.writeln('  /// Creates a new record');
    if (_hasModelImport) {
      buffer.writeln(
          '  Future<$modelClassName> create($modelClassName data) async {');
      buffer.writeln('    final response = await _client');
      buffer.writeln('        .from(tableName)');
      buffer.writeln('        .insert(data.toJson())');
      buffer.writeln('        .select()');
      buffer.writeln('        .single();');
      buffer.writeln('    return $modelClassName.fromJson(response);');
    } else {
      buffer.writeln(
          '  Future<Map<String, dynamic>> create(Map<String, dynamic> data) async {');
      buffer.writeln('    final response = await _client');
      buffer.writeln('        .from(tableName)');
      buffer.writeln('        .insert(data)');
      buffer.writeln('        .select()');
      buffer.writeln('        .single();');
      buffer.writeln('    return response;');
    }
    buffer.writeln('  }');
    buffer.writeln();

    // update method
    buffer.writeln('  /// Updates an existing record');
    if (_hasModelImport) {
      buffer.writeln(
          '  Future<$modelClassName> update($pkDartType $pkName, $modelClassName data) async {');
      buffer.writeln('    final response = await _client');
      buffer.writeln('        .from(tableName)');
      buffer.writeln('        .update(data.toJson())');
      buffer.writeln("        .eq('$pkName', $pkName)");
      buffer.writeln('        .select()');
      buffer.writeln('        .single();');
      buffer.writeln('    return $modelClassName.fromJson(response);');
    } else {
      buffer.writeln(
          '  Future<Map<String, dynamic>> update($pkDartType $pkName, Map<String, dynamic> data) async {');
      buffer.writeln('    final response = await _client');
      buffer.writeln('        .from(tableName)');
      buffer.writeln('        .update(data)');
      buffer.writeln("        .eq('$pkName', $pkName)");
      buffer.writeln('        .select()');
      buffer.writeln('        .single();');
      buffer.writeln('    return response;');
    }
    buffer.writeln('  }');
    buffer.writeln();

    // delete method
    buffer.writeln('  /// Deletes a record by $pkName');
    buffer.writeln('  Future<void> delete($pkDartType $pkName) async {');
    buffer.writeln('    await _client');
    buffer.writeln('        .from(tableName)');
    buffer.writeln('        .delete()');
    buffer.writeln("        .eq('$pkName', $pkName);");
    buffer.writeln('  }');
    buffer.writeln();

    // count method
    buffer.writeln('  /// Gets the total count of records');
    buffer.writeln('  Future<int> count() async {');
    buffer.writeln('    final response = await _client');
    buffer.writeln('        .from(tableName)');
    buffer.writeln('        .select()');
    buffer.writeln('        .count(CountOption.exact);');
    buffer.writeln('    return response.count;');
    buffer.writeln('  }');
    buffer.writeln();

    // paginate method
    buffer.writeln('  /// Fetches records with pagination');
    if (_hasModelImport) {
      buffer.writeln(
          '  Future<List<$modelClassName>> paginate({int page = 1, int perPage = 20}) async {');
      buffer.writeln('    final from = (page - 1) * perPage;');
      buffer.writeln('    final to = from + perPage - 1;');
      buffer.writeln('    final response = await _client');
      buffer.writeln('        .from(tableName)');
      buffer.writeln('        .select()');
      buffer.writeln('        .range(from, to);');
      buffer.writeln(
          '    return response.map((e) => $modelClassName.fromJson(e)).toList();');
    } else {
      buffer.writeln(
          '  Future<List<Map<String, dynamic>>> paginate({int page = 1, int perPage = 20}) async {');
      buffer.writeln('    final from = (page - 1) * perPage;');
      buffer.writeln('    final to = from + perPage - 1;');
      buffer.writeln('    final response = await _client');
      buffer.writeln('        .from(tableName)');
      buffer.writeln('        .select()');
      buffer.writeln('        .range(from, to);');
      buffer.writeln('    return response;');
    }
    buffer.writeln('  }');

    // Generate relation methods for foreign keys
    for (final column in table.columns) {
      if (column.foreignKey != null) {
        final fk = column.foreignKey!;
        final relationName = _getRelationName(column.name);

        buffer.writeln();
        buffer.writeln(
            '  /// Fetches records with $relationName relation embedded');
        if (_hasModelImport) {
          buffer.writeln(
              '  Future<List<$modelClassName>> getAllWith${ReCase(relationName).pascalCase}() async {');
          buffer.writeln('    final response = await _client');
          buffer.writeln('        .from(tableName)');
          buffer.writeln(
              "        .select('*, $relationName:${fk.referencedTable}(*)');");
          buffer.writeln(
              '    return response.map((e) => $modelClassName.fromJson(e)).toList();');
        } else {
          buffer.writeln(
              '  Future<List<Map<String, dynamic>>> getAllWith${ReCase(relationName).pascalCase}() async {');
          buffer.writeln('    final response = await _client');
          buffer.writeln('        .from(tableName)');
          buffer.writeln(
              "        .select('*, $relationName:${fk.referencedTable}(*)');");
          buffer.writeln('    return response;');
        }
        buffer.writeln('  }');
      }
    }

    // Embed custom methods from .custom.dart as instance methods
    if (customContent != null) {
      buffer.writeln();
      buffer.write(customContent.body);
    }

    buffer.writeln('}');

    // Generate Riverpod provider if enabled
    if (_config?.generateProviders == true) {
      buffer.writeln();
      final providerName = ReCase(table.name).camelCase;
      buffer.writeln('/// Provider for [$repoClassName]');
      buffer.writeln('@Riverpod(keepAlive: true)');
      buffer.writeln(
        '$repoClassName ${providerName}Repository(Ref ref) {',
      );
      buffer.writeln(
        '  final client = ref.watch(supabaseClientProvider);',
      );
      buffer.writeln('  return $repoClassName(client);');
      buffer.writeln('}');
    }

    return buffer.toString();
  }

  /// Generates an in-memory fake repository for [table].
  ///
  /// The returned class `implements` the real repository so it can be
  /// substituted via Riverpod overrides or constructor injection in
  /// tests. Standard CRUD methods operate on an in-memory map keyed
  /// by primary key value; relation methods fall back to [getAll];
  /// custom methods are stubbed with [UnimplementedError] so callers
  /// can override them in subclasses for test-specific behavior.
  String generateFake(
    TableInfo table, {
    CustomFileContent? customContent,
  }) {
    final modelClassName = getModelClassName(table.name);
    final repoClassName = getRepositoryClassName(table.name);
    final fakeClassName = getFakeClassName(table.name);
    final repoFileName = getFileName(table.name);
    final tableName = table.name;

    final primaryKey = table.columns.firstWhere(
      (c) => c.isPrimaryKey,
      orElse: () => table.columns.firstWhere(
        (c) => c.name == 'id',
        orElse: () => table.columns.first,
      ),
    );
    final pkName = primaryKey.name;
    final pkDartType = TypeMapper.mapType(primaryKey.dataType);
    final recordType = _hasModelImport ? modelClassName : 'Map<String, dynamic>';
    final pkFromRecord = _hasModelImport
        ? "record.toJson()['$pkName']"
        : "record['$pkName']";

    final buffer = StringBuffer();

    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by suparepo');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln(
      '// ignore_for_file: public_member_api_docs, '
      'sort_constructors_first, lines_longer_than_80_chars',
    );
    buffer.writeln(
      '// ignore_for_file: directives_ordering, '
      'unnecessary_lambdas, avoid_redundant_argument_values',
    );
    buffer.writeln();

    buffer.writeln("import '$_supabaseImport';");
    if (_config?.modelImportPrefix != null) {
      final modelFile = '${ReCase(table.name).snakeCase}.supafreeze.dart';
      buffer.writeln("import '${_config!.modelImportPrefix}$modelFile';");
    } else if (_hasModelImport) {
      buffer.writeln("import '${_config!.modelImportPath}';");
    }
    if (customContent != null) {
      final existingCode = buffer.toString();
      for (final imp in customContent.imports) {
        if (!existingCode.contains(imp)) {
          buffer.writeln(imp);
        }
      }
    }
    buffer.writeln("import '$repoFileName';");
    buffer.writeln();

    buffer.writeln('/// In-memory fake of [$repoClassName] for tests.');
    buffer.writeln('///');
    buffer.writeln('/// CRUD methods operate on [store] keyed by `$pkName`.');
    buffer.writeln('/// Relation methods fall back to [getAll]. Custom methods');
    buffer.writeln('/// throw [UnimplementedError] — override in a subclass to');
    buffer.writeln('/// provide test-specific behavior.');
    buffer.writeln('class $fakeClassName implements $repoClassName {');
    buffer.writeln('  /// In-memory record store keyed by primary key value.');
    buffer.writeln('  final Map<dynamic, $recordType> store;');
    buffer.writeln();
    buffer.writeln(
      '  $fakeClassName({Map<dynamic, $recordType>? initial})',
    );
    buffer.writeln('      : store = {...?initial};');
    buffer.writeln();
    buffer.writeln('  /// Replaces [store] contents with [records].');
    buffer.writeln('  void seed(Iterable<$recordType> records) {');
    buffer.writeln('    store.clear();');
    buffer.writeln('    for (final record in records) {');
    buffer.writeln('      store[$pkFromRecord] = record;');
    buffer.writeln('    }');
    buffer.writeln('  }');
    buffer.writeln();

    buffer.writeln('  @override');
    buffer.writeln("  String get tableName => '$tableName';");
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  SupabaseClient get client => throw UnimplementedError(');
    buffer.writeln(
      "        '$fakeClassName does not expose a SupabaseClient. '",
    );
    buffer.writeln(
      "        'Override methods that require it.',",
    );
    buffer.writeln('      );');
    buffer.writeln();

    buffer.writeln('  @override');
    buffer.writeln(
      '  Future<List<$recordType>> getAll() async => store.values.toList();',
    );
    buffer.writeln();

    buffer.writeln('  @override');
    buffer.writeln(
      '  Future<$recordType?> getById($pkDartType $pkName) async =>',
    );
    buffer.writeln('      store[$pkName];');
    buffer.writeln();

    buffer.writeln('  @override');
    buffer.writeln(
      '  Future<$recordType> create($recordType data) async {',
    );
    buffer.writeln('    final record = data;');
    buffer.writeln('    store[$pkFromRecord] = record;');
    buffer.writeln('    return record;');
    buffer.writeln('  }');
    buffer.writeln();

    buffer.writeln('  @override');
    buffer.writeln(
      '  Future<$recordType> update($pkDartType $pkName, $recordType data) '
      'async {',
    );
    buffer.writeln('    store[$pkName] = data;');
    buffer.writeln('    return data;');
    buffer.writeln('  }');
    buffer.writeln();

    buffer.writeln('  @override');
    buffer.writeln('  Future<void> delete($pkDartType $pkName) async {');
    buffer.writeln('    store.remove($pkName);');
    buffer.writeln('  }');
    buffer.writeln();

    buffer.writeln('  @override');
    buffer.writeln('  Future<int> count() async => store.length;');
    buffer.writeln();

    buffer.writeln('  @override');
    buffer.writeln(
      '  Future<List<$recordType>> paginate({int page = 1, int perPage = 20}) '
      'async {',
    );
    buffer.writeln('    final from = (page - 1) * perPage;');
    buffer.writeln('    final all = store.values.toList();');
    buffer.writeln('    if (from >= all.length) return [];');
    buffer.writeln('    final to = (from + perPage).clamp(0, all.length);');
    buffer.writeln('    return all.sublist(from, to);');
    buffer.writeln('  }');

    for (final column in table.columns) {
      if (column.foreignKey == null) continue;
      final relationName = _getRelationName(column.name);
      final methodName =
          'getAllWith${ReCase(relationName).pascalCase}';
      buffer.writeln();
      buffer.writeln('  @override');
      buffer.writeln(
        '  Future<List<$recordType>> $methodName() => getAll();',
      );
    }

    if (customContent != null) {
      final migrator = CustomMethodMigrator();
      final members = migrator.parseExtensionMembers(customContent.body);
      for (final member in members) {
        // Private members are not part of the public interface
        // and cannot be `@override`-d from a separate library.
        if (member.name.startsWith('_')) continue;
        final signature = migrator.extractMemberSignature(member.source);
        if (signature == null) continue;
        final cleaned = _stripLeadingDocsAndAnnotations(signature);
        if (cleaned.isEmpty) continue;
        buffer.writeln();
        buffer.writeln('  @override');
        for (final line in cleaned.split('\n')) {
          buffer.writeln('  ${line.trimLeft()}');
        }
        buffer.writeln('      => throw UnimplementedError(');
        buffer.writeln(
          "        '$fakeClassName.${member.name} is not faked. '",
        );
        buffer.writeln(
          "        'Override in a subclass to provide test behavior.',",
        );
        buffer.writeln('      );');
      }
    }

    buffer.writeln('}');

    return buffer.toString();
  }

  /// Strip leading doc comments, regular comments, and annotations
  /// from a parsed signature so the stub can prepend a single `@override`.
  String _stripLeadingDocsAndAnnotations(String signature) {
    final lines = signature.split('\n');
    final out = <String>[];
    var skipLeading = true;
    for (final line in lines) {
      final trimmed = line.trim();
      if (skipLeading) {
        if (trimmed.isEmpty ||
            trimmed.startsWith('///') ||
            trimmed.startsWith('//') ||
            trimmed.startsWith('@')) {
          continue;
        }
        skipLeading = false;
      }
      out.add(line);
    }
    return out.join('\n').trim();
  }

  /// Gets the relation name from a foreign key column name
  String _getRelationName(String columnName) {
    if (columnName.endsWith('_id')) {
      return columnName.substring(0, columnName.length - 3);
    }
    return columnName;
  }

  /// Generates all repositories and returns a map of filename to content.
  ///
  /// When [customContents] is provided, maps table name to custom file
  /// content for embedding.
  Map<String, String> generateAllRepositories(
    List<TableInfo> tables, {
    Map<String, CustomFileContent> customContents = const {},
  }) {
    final result = <String, String>{};

    for (final table in tables) {
      final fileName = getFileName(table.name);
      result[fileName] = generateRepository(
        table,
        customContent: customContents[table.name],
      );
      if (_config?.generateFakes == true) {
        result[getFakeFileName(table.name)] = generateFake(
          table,
          customContent: customContents[table.name],
        );
      }
    }

    // Generate barrel file if enabled
    if (_config?.generateBarrel == true) {
      result['repositories.dart'] = generateBarrelFile(tables);
    }

    // Generate supabase_client_provider.dart if providers are enabled
    // When clientProviderOutput is set, the file is handled separately
    // by the CLI (written to the custom path).
    if (_config?.generateProviders == true &&
        _config?.clientProviderOutput == null) {
      result['supabase_client_provider.dart'] =
          generateSupabaseClientProvider();
    }

    return result;
  }

  /// Generates the SupabaseClient provider file.
  ///
  /// When [rpcClientImport] is provided, a SupabaseRpcClient provider is
  /// also generated. When [edgeFunctionClientImport] is provided, a
  /// SupabaseEdgeFunctionClient provider is also generated.
  String generateSupabaseClientProvider({
    String? rpcClientImport,
    String? edgeFunctionClientImport,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by suparepo');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln(
      '// ignore_for_file: public_member_api_docs, '
      'lines_longer_than_80_chars',
    );
    buffer.writeln();
    buffer.writeln(
      "import 'package:riverpod_annotation/riverpod_annotation.dart';",
    );
    buffer.writeln("import '$_supabaseImport';");
    if (rpcClientImport != null) {
      buffer.writeln("import '$rpcClientImport';");
    }
    if (edgeFunctionClientImport != null) {
      buffer.writeln("import '$edgeFunctionClientImport';");
    }
    buffer.writeln();
    buffer.writeln("part 'supabase_client_provider.g.dart';");
    buffer.writeln();
    buffer.writeln(
      '/// SupabaseClient provider.',
    );
    buffer.writeln(
      '/// Must be overridden in ProviderScope.',
    );
    buffer.writeln('@Riverpod(keepAlive: true)');
    buffer.writeln('SupabaseClient supabaseClient(Ref ref) {');
    buffer.writeln('  throw UnimplementedError(');
    buffer.writeln(
      "    'supabaseClientProvider must be overridden "
      "in ProviderScope.',",
    );
    buffer.writeln('  );');
    buffer.writeln('}');

    if (rpcClientImport != null) {
      buffer.writeln();
      buffer.writeln('/// Provider for [SupabaseRpcClient]');
      buffer.writeln('@Riverpod(keepAlive: true)');
      buffer.writeln(
        'SupabaseRpcClient supabaseRpcClient(Ref ref) {',
      );
      buffer.writeln(
        '  final client = ref.watch(supabaseClientProvider);',
      );
      buffer.writeln('  return SupabaseRpcClient(client);');
      buffer.writeln('}');
    }

    if (edgeFunctionClientImport != null) {
      buffer.writeln();
      buffer.writeln(
        '/// Provider for [SupabaseEdgeFunctionClient]',
      );
      buffer.writeln('@Riverpod(keepAlive: true)');
      buffer.writeln(
        'SupabaseEdgeFunctionClient '
        'supabaseEdgeFunctionClient(Ref ref) {',
      );
      buffer.writeln(
        '  final client = ref.watch(supabaseClientProvider);',
      );
      buffer.writeln(
        '  return SupabaseEdgeFunctionClient(client);',
      );
      buffer.writeln('}');
    }

    return buffer.toString();
  }

  /// Generates a separate `client_providers.dart` file containing
  /// RPC and/or EdgeFunction providers.
  ///
  /// This file lives in the data package and imports supabaseClient
  /// from the gateway package via [clientProviderImport].
  String generateClientProviders({
    required String clientProviderImport,
    String? rpcClientImport,
    String? edgeFunctionClientImport,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by suparepo');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln(
      '// ignore_for_file: public_member_api_docs, '
      'lines_longer_than_80_chars',
    );
    buffer.writeln();
    buffer.writeln(
      "import 'package:riverpod_annotation/riverpod_annotation.dart';",
    );
    buffer.writeln("import '$clientProviderImport';");
    if (rpcClientImport != null) {
      buffer.writeln("import '$rpcClientImport';");
    }
    if (edgeFunctionClientImport != null) {
      buffer.writeln("import '$edgeFunctionClientImport';");
    }
    buffer.writeln();
    buffer.writeln("part 'client_providers.g.dart';");
    buffer.writeln();

    if (rpcClientImport != null) {
      buffer.writeln('/// Provider for [SupabaseRpcClient]');
      buffer.writeln('@Riverpod(keepAlive: true)');
      buffer.writeln(
        'SupabaseRpcClient supabaseRpcClient(Ref ref) {',
      );
      buffer.writeln(
        '  final client = ref.watch(supabaseClientProvider);',
      );
      buffer.writeln('  return SupabaseRpcClient(client);');
      buffer.writeln('}');
    }

    if (edgeFunctionClientImport != null) {
      if (rpcClientImport != null) buffer.writeln();
      buffer.writeln(
        '/// Provider for [SupabaseEdgeFunctionClient]',
      );
      buffer.writeln('@Riverpod(keepAlive: true)');
      buffer.writeln(
        'SupabaseEdgeFunctionClient '
        'supabaseEdgeFunctionClient(Ref ref) {',
      );
      buffer.writeln(
        '  final client = ref.watch(supabaseClientProvider);',
      );
      buffer.writeln(
        '  return SupabaseEdgeFunctionClient(client);',
      );
      buffer.writeln('}');
    }

    return buffer.toString();
  }

  /// Generates a barrel file that exports all repositories
  String generateBarrelFile(List<TableInfo> tables) {
    final buffer = StringBuffer();
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by suparepo');
    buffer.writeln('// ignore_for_file: type=lint, directives_ordering');
    buffer.writeln();

    for (final table in tables) {
      final fileName = getFileName(table.name);
      buffer.writeln("export '$fileName';");
    }

    return buffer.toString();
  }
}
