import 'package:recase/recase.dart';
import 'package:supabase_schema_core/supabase_schema_core.dart';
import 'config_loader.dart';
import 'rpc_result_model_generator.dart';

/// Dart reserved words that need escaping in parameter names
const Set<String> _dartReservedWords = {
  'assert',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'default',
  'do',
  'else',
  'enum',
  'extends',
  'false',
  'final',
  'finally',
  'for',
  'if',
  'in',
  'is',
  'new',
  'null',
  'rethrow',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'var',
  'void',
  'while',
  'with',
  'abstract',
  'as',
  'covariant',
  'deferred',
  'dynamic',
  'export',
  'extension',
  'external',
  'factory',
  'function',
  'get',
  'implements',
  'import',
  'interface',
  'late',
  'library',
  'mixin',
  'operator',
  'part',
  'required',
  'set',
  'static',
  'typedef',
  'async',
  'await',
  'yield',
};

/// Applies YAML `return_types` overrides to RPC functions.
///
/// Values can be a PG type name (e.g. `text`, `bool`, `jsonb`)
/// or `setof <type>` to indicate `returnsSetOf: true`.
List<RpcFunctionInfo> applyReturnTypeOverrides(
  List<RpcFunctionInfo> functions,
  Map<String, String> returnTypes,
) {
  return functions.map((func) {
    final override = returnTypes[func.name];
    if (override == null) return func;

    final trimmed = override.trim().toLowerCase();
    if (trimmed.startsWith('setof ')) {
      final type = trimmed.substring(6).trim();
      return func.copyWith(returnType: type, returnsSetOf: true);
    }
    return func.copyWith(returnType: trimmed, returnsSetOf: false);
  }).toList();
}

/// Generates a Supabase RPC client class from RPC function info
class RpcGenerator {
  bool _generateResultModels = false;

  /// Generates the full RPC client file content.
  ///
  /// When [generateResultModels] is true, functions with
  /// [tableColumns] use typed result model classes instead
  /// of `Map<String, dynamic>`.
  String generateRpcClient(
    List<RpcFunctionInfo> functions, {
    String supabaseImport = defaultSupabaseImport,
    bool generateResultModels = false,
    String? resultModelsImportPrefix,
  }) {
    final buffer = StringBuffer();

    // Header
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by suparepo');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln(
      '// ignore_for_file: public_member_api_docs, '
      'sort_constructors_first, lines_longer_than_80_chars',
    );
    buffer.writeln(
      '// ignore_for_file: directives_ordering, '
      'always_put_required_named_parameters_first',
    );
    buffer.writeln(
      '// ignore_for_file: use_null_aware_elements',
    );
    buffer.writeln();

    // Imports
    buffer.writeln("import '$supabaseImport';");

    // Import result model files
    if (generateResultModels) {
      final prefix = resultModelsImportPrefix ?? '';
      for (final func in functions) {
        if (func.tableColumns != null && func.tableColumns!.isNotEmpty) {
          final fileName = RpcResultModelGenerator.resultFileName(func.name);
          buffer.writeln("import '$prefix$fileName';");
        }
      }
    }

    buffer.writeln();

    // Class definition
    buffer.writeln('/// Type-safe RPC client for Supabase functions');
    buffer.writeln('class SupabaseRpcClient {');
    buffer.writeln('  final SupabaseClient _client;');
    buffer.writeln();
    buffer.writeln('  const SupabaseRpcClient(this._client);');

    _generateResultModels = generateResultModels;
    for (final func in functions) {
      buffer.writeln();
      _generateMethod(buffer, func);
    }

    buffer.writeln('}');

    return buffer.toString();
  }

  void _generateMethod(StringBuffer buffer, RpcFunctionInfo func) {
    final methodName = ReCase(func.name).camelCase;
    final dartReturnType = _buildReturnType(func);

    // Doc comment
    if (func.description != null) {
      buffer.writeln('  /// ${func.description}');
    }

    // Method signature
    buffer.write('  Future<$dartReturnType> $methodName(');

    if (func.params.isNotEmpty) {
      // Sort: required params first, then optional
      final sortedParams = List.of(func.params)
        ..sort((a, b) {
          if (a.isRequired == b.isRequired) return 0;
          return a.isRequired ? -1 : 1;
        });

      buffer.writeln('{');
      for (final param in sortedParams) {
        final paramName = _escapeParamName(
          ReCase(param.name).camelCase,
        );
        final paramType = TypeMapper.mapType(param.dataType);

        if (param.isRequired) {
          buffer.writeln(
            '    required $paramType $paramName,',
          );
        } else {
          buffer.writeln('    $paramType? $paramName,');
        }
      }
      buffer.write('  }');
    }

    buffer.writeln(') async {');

    // Method body
    final isVoid = dartReturnType == 'void';
    final isScalar = !isVoid && !func.returnsSetOf;
    final String prefix;
    final String typeArg;

    if (isVoid) {
      prefix = '    await';
      typeArg = 'void';
    } else if (isScalar) {
      prefix = '    return await';
      typeArg = dartReturnType;
    } else {
      prefix = '    final response = await';
      typeArg = 'List<dynamic>';
    }

    if (func.params.isNotEmpty) {
      buffer.write(
        "$prefix _client.rpc<$typeArg>('${func.name}', "
        'params: {',
      );
      buffer.writeln();
      for (final param in func.params) {
        final paramName = _escapeParamName(
          ReCase(param.name).camelCase,
        );
        final value = _serializeParam(paramName, param);
        if (param.isRequired) {
          buffer.writeln(
            "      '${param.name}': $value,",
          );
        } else {
          buffer.writeln(
            "      if ($paramName != null) "
            "'${param.name}': $value,",
          );
        }
      }
      buffer.writeln('    });');
    } else {
      buffer.writeln(
        "$prefix _client.rpc<$typeArg>('${func.name}');",
      );
    }

    // Return statement (only needed for setof)
    _generateReturn(buffer, func, dartReturnType);

    buffer.writeln('  }');
  }

  void _generateReturn(
    StringBuffer buffer,
    RpcFunctionInfo func,
    String dartReturnType,
  ) {
    // void and scalar are handled inline (await / return await)
    if (!func.returnsSetOf && !_hasResultModel(func)) return;

    if (_hasResultModel(func)) {
      final className = RpcResultModelGenerator.resultClassName(func.name);
      buffer.writeln(
        '    return response.cast<Map<String, dynamic>>()',
      );
      buffer.writeln(
        '        .map($className.fromRow).toList();',
      );
      return;
    }

    final itemType = TypeMapper.mapType(func.returnType);
    buffer.writeln(
      '    return response.cast<$itemType>();',
    );
  }

  /// Whether the function should use a typed result model.
  bool _hasResultModel(RpcFunctionInfo func) =>
      _generateResultModels &&
      func.tableColumns != null &&
      func.tableColumns!.isNotEmpty;

  String _buildReturnType(RpcFunctionInfo func) {
    if (func.returnType == 'void') return 'void';

    if (_hasResultModel(func)) {
      final className = RpcResultModelGenerator.resultClassName(func.name);
      return 'List<$className>';
    }

    final dartType = TypeMapper.mapType(func.returnType);
    if (func.returnsSetOf) {
      return 'List<$dartType>';
    }
    return dartType;
  }

  String _escapeParamName(String name) {
    if (_dartReservedWords.contains(name)) {
      return '$name\$';
    }
    return name;
  }

  /// Returns the serialization expression for a parameter value.
  ///
  /// DateTime parameters need to be converted to ISO8601 strings
  /// before being passed to `_client.rpc()`, because `jsonEncode`
  /// cannot serialize DateTime objects directly.
  ///
  /// - `date` → `YYYY-MM-DD` (date-only portion)
  /// - `timestamp` / `timestamptz` → full ISO8601 string
  String _serializeParam(String paramName, RpcParamInfo param) {
    if (!TypeMapper.isDateTimeType(param.dataType)) {
      return paramName;
    }
    if (TypeMapper.isDateOnlyType(param.dataType)) {
      return "$paramName.toIso8601String().split('T').first";
    }
    return '$paramName.toIso8601String()';
  }
}
