import 'package:recase/recase.dart';
import 'package:supabase_schema_core/supabase_schema_core.dart';
import 'config_loader.dart';

/// Dart reserved words that need escaping in parameter names
const Set<String> _dartReservedWords = {
  'assert',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'default',
  'do',
  'else',
  'enum',
  'extends',
  'false',
  'final',
  'finally',
  'for',
  'if',
  'in',
  'is',
  'new',
  'null',
  'rethrow',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'var',
  'void',
  'while',
  'with',
  'abstract',
  'as',
  'covariant',
  'deferred',
  'dynamic',
  'export',
  'extension',
  'external',
  'factory',
  'function',
  'get',
  'implements',
  'import',
  'interface',
  'late',
  'library',
  'mixin',
  'operator',
  'part',
  'required',
  'set',
  'static',
  'typedef',
  'async',
  'await',
  'yield',
};

/// Generates a Supabase RPC client class from RPC function info
class RpcGenerator {
  /// Generates the full RPC client file content
  String generateRpcClient(
    List<RpcFunctionInfo> functions, {
    String supabaseImport = defaultSupabaseImport,
    bool generateProviders = false,
    String? clientProviderImport,
  }) {
    final buffer = StringBuffer();

    // Header
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by suparepo');
    buffer.writeln('// ignore_for_file: type=lint');
    buffer.writeln(
      '// ignore_for_file: public_member_api_docs, '
      'sort_constructors_first, lines_longer_than_80_chars',
    );
    buffer.writeln(
      '// ignore_for_file: directives_ordering, '
      'always_put_required_named_parameters_first',
    );
    buffer.writeln(
      '// ignore_for_file: use_null_aware_elements',
    );
    buffer.writeln();

    // Imports
    if (generateProviders) {
      buffer.writeln(
        "import 'package:riverpod_annotation/riverpod_annotation.dart';",
      );
    }
    buffer.writeln("import '$supabaseImport';");
    if (generateProviders) {
      buffer.writeln();
      final providerImport =
          clientProviderImport ?? 'supabase_client_provider.dart';
      buffer.writeln("import '$providerImport';");
      buffer.writeln();
      buffer.writeln("part 'rpc_client.g.dart';");
    }
    buffer.writeln();

    // Class definition
    buffer.writeln('/// Type-safe RPC client for Supabase functions');
    buffer.writeln('class SupabaseRpcClient {');
    buffer.writeln('  final SupabaseClient _client;');
    buffer.writeln();
    buffer.writeln('  const SupabaseRpcClient(this._client);');

    for (final func in functions) {
      buffer.writeln();
      _generateMethod(buffer, func);
    }

    buffer.writeln('}');

    // Generate Riverpod provider if enabled
    if (generateProviders) {
      buffer.writeln();
      buffer.writeln('/// Provider for [SupabaseRpcClient]');
      buffer.writeln('@Riverpod(keepAlive: true)');
      buffer.writeln(
        'SupabaseRpcClient supabaseRpcClient(Ref ref) {',
      );
      buffer.writeln(
        '  final client = ref.watch(supabaseClientProvider);',
      );
      buffer.writeln('  return SupabaseRpcClient(client);');
      buffer.writeln('}');
    }

    return buffer.toString();
  }

  void _generateMethod(StringBuffer buffer, RpcFunctionInfo func) {
    final methodName = ReCase(func.name).camelCase;
    final dartReturnType = _buildReturnType(func);

    // Doc comment
    if (func.description != null) {
      buffer.writeln('  /// ${func.description}');
    }

    // Method signature
    buffer.write('  Future<$dartReturnType> $methodName(');

    if (func.params.isNotEmpty) {
      // Sort: required params first, then optional
      final sortedParams = List.of(func.params)
        ..sort((a, b) {
          if (a.isRequired == b.isRequired) return 0;
          return a.isRequired ? -1 : 1;
        });

      buffer.writeln('{');
      for (final param in sortedParams) {
        final paramName = _escapeParamName(
          ReCase(param.name).camelCase,
        );
        final paramType = TypeMapper.mapType(param.dataType);

        if (param.isRequired) {
          buffer.writeln(
            '    required $paramType $paramName,',
          );
        } else {
          buffer.writeln('    $paramType? $paramName,');
        }
      }
      buffer.write('  }');
    }

    buffer.writeln(') async {');

    // Method body
    final isVoid = dartReturnType == 'void';
    final prefix = isVoid ? '    await' : '    final response = await';
    final typeArg = isVoid ? 'void' : 'dynamic';

    if (func.params.isNotEmpty) {
      buffer.write(
        "$prefix _client.rpc<$typeArg>('${func.name}', "
        'params: {',
      );
      buffer.writeln();
      for (final param in func.params) {
        final paramName = _escapeParamName(
          ReCase(param.name).camelCase,
        );
        if (param.isRequired) {
          buffer.writeln(
            "      '${param.name}': $paramName,",
          );
        } else {
          buffer.writeln(
            "      if ($paramName != null) "
            "'${param.name}': $paramName,",
          );
        }
      }
      buffer.writeln('    });');
    } else {
      buffer.writeln(
        "$prefix _client.rpc<$typeArg>('${func.name}');",
      );
    }

    // Return statement
    _generateReturn(buffer, func, dartReturnType);

    buffer.writeln('  }');
  }

  void _generateReturn(
    StringBuffer buffer,
    RpcFunctionInfo func,
    String dartReturnType,
  ) {
    if (dartReturnType == 'void') {
      return;
    }

    if (func.returnsSetOf) {
      final itemType = TypeMapper.mapType(func.returnType);
      if (itemType == 'Map<String, dynamic>') {
        buffer.writeln(
          '    return (response as List)'
          '.cast<Map<String, dynamic>>();',
        );
      } else {
        buffer.writeln(
          '    return (response as List).cast<$itemType>();',
        );
      }
    } else {
      final scalarType = TypeMapper.mapType(func.returnType);
      buffer.writeln('    return response as $scalarType;');
    }
  }

  String _buildReturnType(RpcFunctionInfo func) {
    if (func.returnType == 'void') return 'void';

    final dartType = TypeMapper.mapType(func.returnType);
    if (func.returnsSetOf) {
      return 'List<$dartType>';
    }
    return dartType;
  }

  String _escapeParamName(String name) {
    if (_dartReservedWords.contains(name)) {
      return '$name\$';
    }
    return name;
  }
}
